p8105_hw2_jg4891
================
2025-09-24

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.2
    ## ✔ ggplot2   4.0.0     ✔ tibble    3.3.0
    ## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
    ## ✔ purrr     1.1.0     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(ggridges)
options(tibble.print_min = 5)
```

## Problem 1

``` r
pols_df <- read_csv("fivethirtyeight_datasets/pols-month.csv") %>%
  janitor::clean_names() %>%
  separate(mon, into = c("year", "month", "day"), sep = '-') %>%
  mutate(
    year  = as.character(year),
    month = as.integer(month),       # "01" -> 1, "02" -> 2
    month = month.name[month],       # full month names
    month = as.character(month),
    president = case_when(
      prez_gop == 1 ~ "Republican",
      prez_dem == 1 ~ "Democratic"
    )
  ) %>%
  select(-prez_gop, -prez_dem, -day)
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
snp_df <- read_csv("fivethirtyeight_datasets/snp.csv") %>%
  janitor::clean_names() %>%
  separate(date, into = c("month", "day", "year"), sep = '/') %>%
  mutate(
    month = as.integer(month),
    year  = as.integer(year),
    year  = ifelse(year < 50, 2000 + year, 1900 + year),
    month = month.name[month],     # full month names
    year  = as.character(year),
    month = as.character(month)
  ) %>%
  select(-day) %>%
  select(year, month, everything())
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
unemploy_df <- read_csv("fivethirtyeight_datasets/unemployment.csv") %>% 
janitor::clean_names() %>% 
pivot_longer(
    cols = jan:dec,                  # columns to pivot
    names_to = "month",              # new column with month names
    values_to = "unemployment_percent" # new column with values
  ) %>% 
  
  mutate(
    month = month.name[match(tolower(month), tolower(month.abb))],
    month = factor(month, levels = month.name, ordered = TRUE),
    year  = as.character(year),
    month = as.character(month)
  )
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
ft_df = left_join(pols_df, snp_df, by = c("year", "month"))
Sd_df = left_join(ft_df, unemploy_df, by = c("year", "month"))
print(Sd_df)
```

    ## # A tibble: 822 × 11
    ##   year  month    gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president close
    ##   <chr> <chr>      <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>     <dbl>
    ## 1 1947  January       23      51     253      23      45     198 Democrat…    NA
    ## 2 1947  February      23      51     253      23      45     198 Democrat…    NA
    ## 3 1947  March         23      51     253      23      45     198 Democrat…    NA
    ## 4 1947  April         23      51     253      23      45     198 Democrat…    NA
    ## 5 1947  May           23      51     253      23      45     198 Democrat…    NA
    ## # ℹ 817 more rows
    ## # ℹ 1 more variable: unemployment_percent <dbl>

Pols_df dataset contains the number of national politicians who are
democratic or republican at any given time from 1947 Jan to 2015 June.
Snp_df dataset includes closing values of the S&P stock index from 1950
Jan to 2015 July. Unemploy_df dataset includes unemployment percentages
from 1948 Jan to 2015 Dec.  This merged dataset reflects number of
republican governors and senators, democratic governors and senators,
and president’s party, and unemployment percentage from 1947 to 2015.

## Problem 2

``` r
  mr_df = 
  readxl::read_excel("Trash.xlsx", sheet="Mr. Trash Wheel", range = "A2:N653",na = c("NA", "", "."))|>
  filter(!is.na(Dumpster)) |> 
  janitor::clean_names() |> 
  mutate(sheet = "Mr. Trash") |> 
  mutate(sports_balls = as.integer(round(sports_balls)))
```

``` r
  pr_df = 
  readxl::read_excel("Trash.xlsx", sheet="Professor Trash Wheel", range = "A2:M120",na = c("NA", "", "."))|>
  filter(!is.na(Dumpster)) |> 
  janitor::clean_names() |> 
  mutate(sheet = "Professor Trash")
```

``` r
  gw_df = 
  readxl::read_excel("Trash.xlsx", sheet="Gwynnda Trash Wheel", range = "A2:L265",na = c("NA", "", "."))|>
   filter(!is.na(Dumpster)) |> 
  janitor::clean_names() |> 
  mutate(sheet = "Gwynnda Trash")
```

``` r
df_tidy = bind_rows(gw_df %>% mutate(year = as.numeric(year)), mr_df%>% mutate(year = as.numeric(year)), pr_df%>% mutate(year = as.numeric(year))) |> 
  janitor::clean_names() |> 
  select(sheet, everything())


pf_wt <- df_tidy %>% 
  filter(sheet == "Professor Trash") %>% 
  summarize(total_weight = sum(weight_tons, na.rm = TRUE)) %>% 
  pull(total_weight)

gw_cb <- df_tidy %>% 
  filter(sheet == "Gwynnda Trash", year=="2022", month=="June") %>% 
  summarize(total_weight = sum(cigarette_butts, na.rm = TRUE)) %>% 
  pull(total_weight)
```

Variables definition: Dumpster shows the code for each dumpster in
numeric value. Sheet is the dataset that each dumpster belong to, such
as Mr. Trash, Professor Trash or Gynnda Trash. Weight_tons is the
weight(tons) for each dumpster. Plastic bottles shows up the number of
plastic bottles in each dumpster. Homes_powered is the energy that trash
generate for home.

In total, we have 1032 observations. In Professor Trash Wheel dataset,
we have total weight of trash of 246.74 tons. In Gwynnda dataset, in
June 2022, we have a total number of cigarette butts collected is
1.812^{4}.

## Problem 3

``` r
z1_df = read_csv("zillow_data/Zip_NYC.csv", na = c("NA", "", ".")) |> 
  janitor::clean_names() |> 
  rename(zip_code=region_name) |> 
  pivot_longer(
    x2015_01_31:x2024_08_31,
    names_to = "time", 
    values_to = "Index") 
```

    ## Rows: 149 Columns: 125
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr   (6): RegionType, StateName, State, City, Metro, CountyName
    ## dbl (119): RegionID, SizeRank, RegionName, 2015-01-31, 2015-02-28, 2015-03-3...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
z2_df <- read_csv("zillow_data/Zipcodes.csv",na = c("NA", "", ".")) |> 
  janitor::clean_names() 
```

    ## Rows: 322 Columns: 7
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (4): County, County Code, File Date, Neighborhood
    ## dbl (3): State FIPS, County FIPS, ZipCode
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
m2_df = left_join(z1_df, z2_df, by="zip_code") |> 
  filter(!is.na(Index)) |> 
  select(-region_type,-state_name,-county_name) |> 
  relocate(time, size_rank, Index,  state, state_fips,  city, zip_code, county, county_fips, county_code, region_id, metro, neighborhood, file_date)
```

``` r
missing_zips <- setdiff(z2_df$zip_code, z1_df$zip_code)
print(missing_zips)
```

    ##   [1] 10464 10474 10475 10499 10550 10704 10705 10803 11202 11224 11239 11241
    ##  [13] 11242 11243 11245 11247 11251 11252 11256 10008 10020 10041 10043 10045
    ##  [25] 10047 10048 10055 10072 10080 10081 10082 10087 10101 10102 10103 10104
    ##  [37] 10105 10106 10107 10108 10109 10110 10111 10112 10113 10114 10115 10116
    ##  [49] 10117 10118 10119 10120 10121 10122 10123 10124 10125 10126 10129 10130
    ##  [61] 10131 10132 10133 10138 10149 10150 10151 10152 10153 10154 10155 10156
    ##  [73] 10157 10158 10159 10160 10161 10163 10164 10165 10166 10167 10168 10169
    ##  [85] 10170 10171 10172 10173 10174 10175 10176 10177 10178 10179 10185 10197
    ##  [97] 10199 10213 10242 10249 10256 10259 10260 10261 10265 10268 10269 10270
    ## [109] 10271 10272 10273 10274 10275 10276 10277 10278 10279 10281 10285 10286
    ## [121] 10292 11001 11004 11005 11040 11096 11351 11352 11359 11362 11363 11371
    ## [133] 11380 11381 11386 11405 11411 11412 11413 11414 11416 11417 11419 11420
    ## [145] 11421 11422 11423 11424 11425 11427 11428 11429 11430 11431 11433 11436
    ## [157] 11439 11451 11499 11559 11580 11690 11694 11695 11697 10302 10307 10309
    ## [169] 10310 10311 10313

Rental prices fluctuated dramatically during the COVID-19 pandemic. For
all available ZIP codes, compare rental prices in January 2021 to prices
in January 2020. Make a table that shows the 10 ZIP codes (along with
the borough and neighborhood) with largest drop in price from January
2020 to 2021. Comment.

``` r
m3_df = m2_df |> 
  janitor::clean_names() |> 
mutate(
    date = ymd(str_remove(time, "^x")),                  # "x2020_01_31" -> Date
    yr   = year(date),
    mo   = month(date)
  ) %>%
  filter(mo == 1, yr %in% c(2020, 2021)) %>%             # keep Jan 2020 & Jan 2021
  # aggregate to one price per ZIP/year (use mean or median)
  group_by(zip_code, city, county, yr) %>%
  summarise(index_sum = sum(index, na.rm = TRUE), .groups = "drop") %>%
  pivot_wider(names_from = yr, values_from = index_sum, names_prefix = "y") %>%
  # keep ZIPs that have both years
  filter(!is.na(y2020), !is.na(y2021)) %>% 
mutate(
    drop = y2020 - y2021
  ) %>%
  arrange(desc(drop)) %>%   
  slice_head(n = 10) %>%
  mutate(
    y2020     = round(y2020, 1),
    y2021     = round(y2021, 1),
    drop      = round(drop, 1)
  ) %>%
  select(zip_code, city, county, y2020, y2021, drop)

# show results
print(m3_df, n = 10)
```

    ## # A tibble: 10 × 6
    ##    zip_code city     county   y2020 y2021  drop
    ##       <dbl> <chr>    <chr>    <dbl> <dbl> <dbl>
    ##  1    10007 New York New York 6334. 5422.  913.
    ##  2    10069 New York New York 4623  3875.  748.
    ##  3    10009 New York New York 3406. 2692.  714.
    ##  4    10016 New York New York 3731. 3019.  712.
    ##  5    10001 New York New York 4108. 3398.  710.
    ##  6    10002 New York New York 3645. 2935.  710.
    ##  7    10004 New York New York 3150. 2444.  706 
    ##  8    10038 New York New York 3573. 2876.  698.
    ##  9    10012 New York New York 3629. 2942.  686.
    ## 10    10010 New York New York 3697. 3012.  685.

There are 10677 observations, 149 unique zip codes, and 43
neighborhoods. 171 zipcodes were missing in the zillow dataset because
it is too narrow, such as 10464, 10474, 10475 and so on.It is part of
military housing so it is not open to public.

Compared rental price in Jan 2020 to Jan 2021, 10007 area has the
biggest fall of 912.6 dollars.
