---
title: "p8105_hw2_jg4891"
output: github_document
date: "2025-09-24"
---

```{r setup}
library(tidyverse)
options(tibble.print_min = 5)

```
## Problem 1
```{r pol_month}
pols_df <- read_csv("fivethirtyeight_datasets/pols-month.csv") %>%
  janitor::clean_names() %>%
  separate(mon, into = c("year", "month", "day"), sep = '-') %>%
  mutate(
    year  = as.character(year),
    month = as.integer(month),       # "01" -> 1, "02" -> 2
    month = month.name[month],       # full month names
    month = as.character(month),
    president = case_when(
      prez_gop == 1 ~ "Republican",
      prez_dem == 1 ~ "Democratic"
    )
  ) %>%
  select(-prez_gop, -prez_dem, -day)
```
```{r snp}
snp_df <- read_csv("fivethirtyeight_datasets/snp.csv") %>%
  janitor::clean_names() %>%
  separate(date, into = c("month", "day", "year"), sep = '/') %>%
  mutate(
    month = as.integer(month),
    year  = as.integer(year),
    year  = ifelse(year < 50, 2000 + year, 1900 + year),
    month = month.name[month],     # full month names
    year  = as.character(year),
    month = as.character(month)
  ) %>%
  select(-day) %>%
  select(year, month, everything())
```
```{r unemploy}
unemploy_df <- read_csv("fivethirtyeight_datasets/unemployment.csv") %>% 
janitor::clean_names() %>% 
pivot_longer(
    cols = jan:dec,                  # columns to pivot
    names_to = "month",              # new column with month names
    values_to = "unemployment_percent" # new column with values
  ) %>% 
  
  mutate(
    month = month.name[match(tolower(month), tolower(month.abb))],
    month = factor(month, levels = month.name, ordered = TRUE),
    year  = as.character(year),
    month = as.character(month)
  )
```
```{r merge}

ft_df = left_join(pols_df, snp_df, by = c("year", "month"))
Sd_df = left_join(ft_df, unemploy_df, by = c("year", "month"))

```




